"""add_parent_review_id_for_follow_up_reviews

Revision ID: 837d7d5b204e
Revises: ca11a859509d
Create Date: 2025-11-07 23:46:37.266269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '837d7d5b204e'
down_revision: Union[str, None] = 'ca11a859509d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('parent_review_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'reviews', 'reviews', ['parent_review_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.drop_column('reviews', 'parent_review_id')
    # ### end Alembic commands ###
