"""add_categories_and_file_upload_support

Revision ID: a37abed7f4a8
Revises: 837d7d5b204e
Create Date: 2025-11-08 10:47:25.880286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a37abed7f4a8'
down_revision: Union[str, None] = '837d7d5b204e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. 先创建 categories 表
    op.create_table('categories',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('parent_id', sa.Integer(), nullable=True),
        sa.Column('level', sa.Integer(), nullable=False),
        sa.Column('description', sa.String(length=500), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_id'), 'categories', ['id'], unique=False)
    
    # 2. 添加 category_id 列（先允许 NULL，以便迁移数据）
    op.add_column('products', sa.Column('category_id', sa.Integer(), nullable=True))
    
    # 3. 创建默认分类并迁移现有数据（如果有的话）
    # 注意：这里需要先创建一些默认分类，然后将现有商品的 category 枚举值映射到分类ID
    # 由于无法在迁移中直接执行 Python 代码查询，我们创建一个默认分类
    op.execute("""
        INSERT INTO categories (name, parent_id, level, description, is_active, created_at, updated_at)
        VALUES 
        ('电子产品', NULL, 1, '各类电子设备', true, now(), now()),
        ('服装服饰', NULL, 1, '各类服装和配饰', true, now(), now()),
        ('家居用品', NULL, 1, '家居装饰和生活用品', true, now(), now()),
        ('图书文教', NULL, 1, '图书和教育用品', true, now(), now())
    """)
    
    # 4. 迁移现有数据：将枚举值映射到分类ID
    # electronics -> 电子产品 (假设是第一个)
    # fashion -> 服装服饰
    # home -> 家居用品
    # books -> 图书文教
    op.execute("""
        UPDATE products 
        SET category_id = (SELECT id FROM categories WHERE name = '电子产品' LIMIT 1)
        WHERE category = 'electronics'
    """)
    op.execute("""
        UPDATE products 
        SET category_id = (SELECT id FROM categories WHERE name = '服装服饰' LIMIT 1)
        WHERE category = 'fashion'
    """)
    op.execute("""
        UPDATE products 
        SET category_id = (SELECT id FROM categories WHERE name = '家居用品' LIMIT 1)
        WHERE category = 'home'
    """)
    op.execute("""
        UPDATE products 
        SET category_id = (SELECT id FROM categories WHERE name = '图书文教' LIMIT 1)
        WHERE category = 'books'
    """)
    
    # 5. 将 category_id 设置为 NOT NULL
    op.alter_column('products', 'category_id', nullable=False)
    
    # 6. 创建外键约束
    op.create_foreign_key('fk_products_category_id', 'products', 'categories', ['category_id'], ['id'])
    
    # 7. 删除旧的 category 枚举列
    op.drop_column('products', 'category')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. 添加回旧的 category 枚举列
    op.add_column('products', sa.Column('category', postgresql.ENUM('electronics', 'fashion', 'home', 'books', name='categoryenum'), autoincrement=False, nullable=True))
    
    # 2. 迁移数据回枚举值（简化处理，默认设为 electronics）
    op.execute("""
        UPDATE products 
        SET category = 'electronics'
        WHERE category IS NULL
    """)
    
    # 3. 设置为 NOT NULL
    op.alter_column('products', 'category', nullable=False)
    
    # 4. 删除外键和 category_id 列
    op.drop_constraint('fk_products_category_id', 'products', type_='foreignkey')
    op.drop_column('products', 'category_id')
    
    # 5. 删除 categories 表
    op.drop_index(op.f('ix_categories_id'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
