"""add_completed_status_to_orders

Revision ID: ca11a859509d
Revises: 3d1990919a27
Create Date: 2025-11-07 23:25:07.343413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca11a859509d'
down_revision: Union[str, None] = '3d1990919a27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 添加 'completed' 状态到 orderstatus 枚举
    op.execute("ALTER TYPE orderstatus ADD VALUE IF NOT EXISTS 'completed'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 注意：PostgreSQL 不支持删除枚举值，需要重建枚举类型
    # 这里不执行回滚操作，保留 'completed' 值
    pass
    # ### end Alembic commands ###
